### ISSUE TITLE
Plasma 5.26 Beta - Window appears before animation plays

### ISSUE THREAD

**Issue by mmcnutt** [Schneegans/Burn-My-Windows#223]
## Describe the Bug
Installed 5.25.90 (plasma 5.26 beta) and the animation and window draw orders are out of sequence for both opening and closing windows. Opening a new Window has the Window appear, play the animation and then redraw the window. Closing a Window has the the animation play over the Window before the Window disappears. If relevant this is a Wayland session

1. Set an effect in Kwin Effects
2. Open Window 
3. Observe Window appears, animation plays over it, Window flickers and then is redrawn
4. Close Window
5. Animation plays over Window, only then does it disappear instead of as the animation plays

## System
_Please complete the following information:_
 - Linux distribution Fedora Rawhide
 - Burn-My-Windows version v21
 - Plasma Shell version: 5.25.90

**Comment by JoseEscobarBendezu** [comment]
On kwin 5.26 this problem persistent.

**Comment by Schneegans** [comment]
Ohh, thanks for pinging me on this issue. This totally slipped through :cry: 

I just tested it on the latest KDE Neon and I can indeed reproduce the issue. I think that it's rather a KWin issue, so I'll open a bug report over there.

**Comment by Schneegans** [comment]
Ok, this was resolved extremely fast by the KDE guys. The fix should be released with KWin 5.26.1 in the coming week! I'll close this issue once it it released.

**Comment by ramon501** [comment]
i am on plasmashell 5.26.0, i cloned the effect to my home directory, ran git pull but i still have this issue, am i missing an extra command or just need to wait the update to kwin 5.26.1 ?

**Comment by Schneegans** [comment]
Yeah, you have to wait for KWin 5.26.1.

**Comment by Churchexe** [comment]
Awesome, glad it's getting sorted out quickly. (seriously I'm still stuck in the windows' "welp, the latest update broke the photoviewer, guess I'll wait a few months" mindset)

**Comment by Schneegans** [comment]
This is now fixed in the latest version of KWin!
