### ISSUE TITLE
Windows don't close on Gnome 48 beta

### ISSUE THREAD

**Issue by Artim96** [Schneegans/Burn-My-Windows#507]
## Describe the Bug
Gnome 48 beta just landed in Debian Testing, but to be usable, this extension needs to be disabled Otherwise when closing a windows (I only have the animations enabled on closing), it's very likely the window freezes up and keeps displaying over everything else, especially gnome-console seems to be affected freezing pretty much every time. I have yet to see anything in the logs, and I obviously can't tell if that's an issue of the extension or if it's an issue in Gnome that will be fixed before the final release, just wanted this as a heads up.

1. Open any window
2. close it

The only lines concerning burn-my-windows that I can find in the logs is this:

 ```
Effect/this.shaderFactory<@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/SnapOfDisintegration.js:54:27
                                    getShader@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/ShaderFactory.js:86:12
                                    _setupEffect@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:574:41
                                    enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:213:29
                                    Effect/this.shaderFactory<@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/BrokenGlass.js:60:28
                                    getShader@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/ShaderFactory.js:86:12
                                    _setupEffect@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:574:41
                                    enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:213:29
                                    Effect/this.shaderFactory<@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/SnapOfDisintegration.js:54:27
                                    getShader@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/ShaderFactory.js:86:12
                                    _setupEffect@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:574:41
                                    enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:213:29
                                    Effect/this.shaderFactory<@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/Matrix.js:52:27
                                    getShader@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/ShaderFactory.js:86:12
                                    _setupEffect@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:574:41
                                    enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:213:29
                                     Effect/this.shaderFactory<@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/TRexAttack.js:50:27
                                     getShader@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/ShaderFactory.js:86:12
                                     _setupEffect@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:574:41
                                     enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/user/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:213:29
```

## System
_Please complete the following information:_
 - Linux distribution: Debian Testing
 - Burn-My-Windows version: 45
 - GNOME Shell version: 48~beta-4

**Comment by SubOptimal** [comment]
Here are some additional information and log entries which might help to identify the reason.

It seems not all effects lead to the issue, or it happens only after some precondition. The issue can be forced to happen by using the preview function a few times for the effects from the logs below.

```
$ lsb_release -d
Description:	Debian GNU/Linux trixie/sid

$ gnome-shell --version
GNOME Shell 48.beta

$ gnome-extensions info burn-my-windows@schneegans.github.com
burn-my-windows@schneegans.github.com
  Name: Burn My Windows
  Description: Disintegrate your windows with style.
  Path: /home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com
  URL: https://github.com/Schneegans/Burn-My-Windows
  Version: 45
  Enabled: Yes
  State: ACTIVE
```

```
StImageContent initialized with invalid preferred size: -1x-1
JS ERROR: TypeError: method St.ImageContent.set_data: At least 6 arguments required, but only 5 passed
Effect/this.shaderFactory<@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/PaintBrush.js:50:28
getShader@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/ShaderFactory.js:86:12
_setupEffect@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:574:41
enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:213:29
_destroyWindow@resource:///org/gnome/shell/ui/windowManager.js:1573:19
@resource:///org/gnome/shell/ui/init.js:21:20
```

```
StImageContent initialized with invalid preferred size: -1x-1
JS ERROR: TypeError: method St.ImageContent.set_data: At least 6 arguments required, but only 5 passed
Effect/this.shaderFactory<@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/SnapOfDisintegration.js:54:27
getShader@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/ShaderFactory.js:86:12
_setupEffect@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:574:41
enable/Main.wm._shouldAnimateActor/actor.ease@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/extension.js:213:29
_destroyWindow@resource:///org/gnome/shell/ui/windowManager.js:1573:19
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:290:16
@resource:///org/gnome/shell/ui/init.js:21:20
```

```
JS ERROR: Error: Argument texture may not be null
Effect/this.shaderFactory</<@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/PaintBrush.js:77:18
vfunc_paint_target@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/Shader.js:201:10
@resource:///org/gnome/shell/ui/init.js:21:20
```

```
JS ERROR: Error: Argument texture may not be null
Effect/this.shaderFactory</<@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/effects/BrokenGlass.js:112:18
vfunc_paint_target@file:///home/<user>/.local/share/gnome-shell/extensions/burn-my-windows@schneegans.github.com/src/Shader.js:201:10
@resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by Schneegans** [comment]
Thanks for the report! I'll look into it. It used to work before, but maybe something was changed again in the beta.

**Comment by Schneegans** [comment]
I think I found the culprit: [This commit](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/44b84e458a22046fedb85701ea25ad08ecc0d43f) changed the API of the `St.ImageContent` used by some BMW effects. Let's see if I can fix this...

**Comment by Schneegans** [comment]
I just merged a fix to `main`. Would be great if anybody from you could test this. If it works, I would soon upload a new version to EGO!

**Comment by Artim96** [comment]
It does seem to work for now. I'd keep an eye out for now, maybe it's not fully fixed. But if you don't get any additional reports on that until Monday, you can probaly rest assured this works and can push it out as release. At least if Gnome doesn't do any last minute changes before the release. There was an article on Phoronix not 24 h ago that Gnome just pushed a bunch of stuff to the RC, this may or may not cause further breakage.

**Comment by SubOptimal** [comment]
With commit db955d5af8 the issue is solved for me.

Thanks for the prompt reaction. 👍

**Comment by Schneegans** [comment]
Thanks for the feedback! Then I'll push a new version.
